defaults:
  - act_config
  - _self_

method: act_right_arm_2cam_100ep
policy_name: act

feature_filter:
  enabled: true
  image_keys:
    - observation.images.head_cam_h
    - observation.images.wrist_cam_r
  state_key: observation.state
  action_key: action
  state_indices: [8, 9, 10, 11, 12, 13, 14, 15]
  action_indices: [8, 9, 10, 11, 12, 13, 14, 15]

training:
  max_epoch: 100
  save_freq_epoch: 10
  open_loop_eval_freq_epoch: 20
  open_loop_eval_max_batches: null
  batch_size: 32
  num_workers: 4
  RGB_Augmenter:
    enable: false

policy:
  use_amp: true
  custom:
    use_depth: false
